models/User.php
<?php
/**
 * @link http://zenothing.com/
*/

namespace app\models;


use app\behaviors\Journal;
use Exception;
use Yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\web\User as WebUser;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * Class User
 * @property integer id
 * @property string name
 * @property string auth
 * @property string email
 * @property string code
 * @property string hash
 * @property string wallet
 * @property integer status
 * @property number account
 * @property integer duration
 * @property string ref_name
 * @property resource data
 * @property array bundle
 * @property User referral
 * @package app\models
 */
class User extends ActiveRecord implements IdentityInterface {

    const BLOCKED = 0;
    const ADMIN = 1;
    const PLAIN = 2;
    const MANAGER = 3;

    private $_password;
    private $_info;

    public static function primaryKey() {
        return ['id'];
    }

    public static function statuses() {
        return [
            User::BLOCKED => Yii::t('app', 'Blocked'),
            User::ADMIN => Yii::t('app', 'Admin'),
            User::PLAIN => Yii::t('app', 'Registered'),
            User::MANAGER => Yii::t('app', 'Manager')
        ];
    }

    public static $events = [
        'login' => 'Вход',
        'logout' => 'Выход',
        'login_fail' => 'Неудачная попытка входа',
    ];

    public function traceable() {
        return ['status', 'email', 'skype',  'perfect', 'account'];
    }

    public function url() {
        return ['user/view', 'name' => $this->name];
    }

    public function rules() {
        return [
            ['id', 'integer'],
            [['name', 'email', 'perfect', 'account'], 'required'],
            ['password', 'required', 'on' => 'signup'],
            ['name', 'string', 'min' => 4, 'max' => 24],
            ['name', 'match', 'pattern' => '/^[a-z][a-z0-9_\-]+$/i', 'on' => 'signup'],
            ['email', 'email'],
            ['perfect', 'match', 'pattern' => '/^U\d{7,8}$/', 'message' =>
                Yii::t('app', 'The wallet should looks like U1234567')],
            ['skype', 'match', 'pattern' => '/^[a-zA-Z][a-zA-Z0-9\.,\-_]{5,31}$/'],
            ['skype', 'default', 'value' => null],
            [['name'], 'filter', 'filter' => 'trim'],
            [['name'], 'unique',
                'targetClass' => 'app\models\User',
                'message' => Yii::t('app', 'This value has already been taken')],
            ['duration', 'integer', 'min' => 0, 'max' => 60 * 24 * 7]
        ];
    }

    public function scenarios() {
        return [
            'default' => ['email', 'skype', 'duration'],
            'signup'  => ['name', 'email', 'skype', 'perfect', 'ref_name', 'password'],
            'admin'   => ['name', 'email', 'skype', 'perfect', 'ref_name', 'account', 'status', 'duration'],
        ];
    }

    public function attributeLabels() {
        return [
            'name' => Yii::t('app', 'Username'),
            'email' => Yii::t('app', 'Email'),
            'password' => Yii::t('app', 'Password'),
            'account' => Yii::t('app', 'Account'),
            'skype' => Yii::t('app', 'Skype'),
            'perfect' => Yii::t('app', 'Perfect Money wallet'),
            'duration' => Yii::t('app', 'Session duration (in minutes)'),
            'ref_name' => Yii::t('app', 'Referral'),
        ];
    }

    public function behaviors() {
        return [
            Journal::className()
        ];
    }

    public function init() {
        parent::init();
        if (isset(Yii::$app->user)
            && Yii::$app->user instanceof WebUser
            && !Yii::$app->user->getIsGuest()
            && static::ADMIN == Yii::$app->user->identity->status) {
            $this->scenario = 'admin';
        }
    }

    /**
     * @param string $id
     * @return User
     */
    public static function findIdentity($id) {
        return parent::findOne(['id' => $id]);
    }

    public static function findIdentityByAccessToken($token, $type = null) {
        throw new Exception('Not implemented findIdentityByAccessToken');
    }

    public function getId() {
        return $this->id;
    }

    public function getAuthKey() {
        return $this->auth;
    }

    public function validateAuthKey($authKey) {
        return $authKey == $this->auth;
    }

    public function validatePassword($password) {
        return password_verify($password, $this->hash);
    }

    public function getPassword() {
        return $this->_password;
    }

    public function setPassword($value) {
        $this->hash = password_hash($value, PASSWORD_DEFAULT);
        $this->_password = $value;
    }

    public function generateAuthKey() {
        $this->auth = Yii::$app->security->generateRandomString(64);
    }

    public function generateCode() {
        $this->code = Yii::$app->security->generateRandomString(64);
    }

    public function isManager() {
        return static::ADMIN == $this->status || static::MANAGER == $this->status;
    }

    public function isAdmin() {
        return static::ADMIN == $this->status;
    }

    public function __toString() {
        return $this->name;
    }

    public function sendEmail($template, $params)
    {
        $template = Yii::getAlias('@app') . "/mail/$template.php";
        return Yii::$app->mailer->compose()
            ->setTo($this->email)
            ->setFrom(['diamond4rush@gmail.com' => Yii::$app->name])
            ->setSubject($params['subject'])
            ->setHtmlBody(Yii::$app->view->renderFile($template, $params))
            ->send();
    }

    public function canLogin() {
        return Record::find()->andWhere([
            'object_id' => $this->id,
            'event' => 'login_fail'
        ])
            ->andWhere('(NOW() - "time") < interval \'10 minutes\'')
            ->count() < 10;
    }

    /**
     * @return User
     */
    public function getReferral() {
        return $this->hasOne(static::className(), ['name' => 'ref_name']);
    }

    public function getBundle() {
        if (!$this->_info) {
            $this->_info = unserialize(stream_get_contents($this->data));
        }
        return $this->_info;
    }

    public function setBundle($value) {
        $value = empty($value) ? null : serialize($value);
        $this->data = $value;
        $this->_info = $value;
    }

    public function setBundleFromAttributes($names, $restore = false) {
        $bundle = [];
        foreach($names as $name) {
            $bundle[$name] = $this->$name;
            if ($restore) {
                $this->$name = $this->getOldAttribute($name);
            }
        }
        $this->setBundle($bundle);
    }

    public function getNodes() {
        return $this->hasMany(Node::className(), ['user_name' => 'name']);
    }

    public function hasNodes() {
        return $this->getNodes()->count() > 0;
    }
}

controllers/MatrixController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use app\models\Invoice;
use app\models\Matrix;
use app\models\Node;
use app\models\search\Income as IncomeSearch;
use app\models\User;
use app\models\Type;
use app\SQL;
use Exception;
use PDO;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\db\Query;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class MatrixController extends Controller
{
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::className(),
                'manager' => ['create', 'update', 'delete', 'up', 'rise']
            ],

            'cache' => [
                'class' => 'yii\filters\PageCache',
                'only' => ['index', 'income', 'invest'],
                'duration' => 600,
                'enabled' => false,
                'variations' => [
                    array_merge(['page' => '1', 'size' => '15', 'order' => 'asc'], $_GET),
                    Yii::$app->user->isGuest
                ],
                'dependency' => [
                    'class' => 'yii\caching\DbDependency',
                    'sql' => 'SELECT max("time") + count(*) FROM "node"',
                ],
            ],
        ];
    }

    protected function matrix($page = 1, $size = 15, $order = 'asc') {
        $count = Matrix::find()->select('count(*) as "count"')->groupBy('type_id')->column();
        $count = empty($count) ? 0 : (int) max($count);
        if ((Yii::$app->user->isGuest || !Yii::$app->user->identity->isManager()) && $size > 100) {
            return $this->redirect(['index', 'size' => 15]);
        }
        $pages = [
            'totalCount' => $count,
            'pageSize' => $size,
            'pageSizeParam' => 'size',
            'page' => $page - 1
        ];

        $pages = new Pagination($pages);

        /** @var Query $query */
        $query = null;
        $types = Type::all();
        $order = 'asc' == $order ? SORT_ASC : SORT_DESC;
        foreach($types as $type) {
            $subquery = Matrix::find()
                ->where(['type_id' => $type->id])
                ->offset($pages->offset)
                ->limit($pages->limit)
                ->orderBy(['time' => $order, 'id' => $order]);
            if ($query) {
                $query->union($subquery);
            }
            else {
                $query = $subquery;
            }
        }

        return [
            'matrix' => $query->all(),
            'pages' => $pages
        ];
    }

    public function actionMatrix($page = 1, $size = 15, $order = 'asc') {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $this->matrix($page, $size, $order);
    }

    public function actionIndex($page = 1, $size = 15, $order = 'asc') {
        $result = $this->matrix($page, $size, $order);
        $table = [];
        foreach($result['matrix'] as $invest) {
            if (empty($table[$invest->type_id - 1])) {
                $table[$invest->type_id - 1] = [];
            }
            $table[$invest->type_id - 1][] = $invest->attributes;
        }

        return $this->render('index', [
            'models' => $table,
            'pages' => $result['pages']
        ]);
    }

    public function actionPlan() {
        $dataProvider = new ActiveDataProvider([
            'query' => Type::find()->where(['enabled' => true]),
            'sort' => [
                'defaultOrder' => ['id' => SORT_ASC]
            ]
        ]);

        $participants = SQL::queryAll('SELECT type_id, count(*) as count
            FROM (SELECT type_id, user_name FROM node GROUP BY type_id, user_name) t GROUP BY type_id', null, PDO::FETCH_KEY_PAIR);

        foreach(Type::all() as $type) {
            if (empty($participants[$type->id])) {
                $participants[$type->id] = 0;
            }
        }

        return $this->render('plan', [
            'dataProvider' => $dataProvider,
            'participants' => $participants
        ]);
    }

    public function actionInvest($user = null, $id = null) {
        $parent = $id ? $this->findNode($id) : null;
        $query = Node::find()
            ->with('type')
            ->orderBy(['time' => SORT_ASC, 'id' => SORT_ASC]);
        if ($user) {
            $query->andWhere(['user_name' => $user]);
        }
        elseif ($parent) {
            $query
                ->andWhere('"time" < :time', [':time' => $parent->time])
                ->andWhere(['type_id' => $parent->type_id]);
        }
        return $this->render('invest', [
            'dataProvider' => new ActiveDataProvider([
                'query' => $query
            ]),
            'parent' => $parent
        ]);
    }

    public function actionRise() {
        $transaction = Yii::$app->db->beginTransaction();
        do {
            $i = Node::rise();
        }
        while($i > 0);
        $transaction->commit();
        return $this->redirect(['/user/account']);
    }

    public function actionUp($id) {
        $invest = $this->findNode($id);
        $transaction = Yii::$app->db->beginTransaction();
        try {
            $invest->up();
            $transaction->commit();
        }
        catch (Exception $ex) {
            $transaction->rollBack();
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(['invest', 'id' => $id]);
    }

    public function actionIncome() {
        $searchModel = new IncomeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('income', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    public function actionView($id) {
        $model = $this->findModel($id);

        if (!Yii::$app->user->isGuest &&
            Yii::$app->user->identity->isManager() &&
            $model->load(Yii::$app->request->post())) {
            $model->save();
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCreate($id = null) {
        $model = new Node();
        if ($id) {
            $base = $this->findNode($id);
            $model->time = $base->time - 1;
            $model->type_id = $base->type_id;
        }
        else {
            $model->time = time();
        }

        $is_post = $model->load(Yii::$app->request->post());
        if ($is_post) {
            $model->count = $model->type->degree;
            if ($is_post && $model->validate()) {
                if (!$model->reinvest_from) {
                    $model->reinvest_from = null;
                }
                if ($model->save(false)) {
                    return $this->redirect(['invest', 'id' => $model->id]);
                }
            }
            else {
                Yii::$app->session->setFlash('error', json_encode($model->errors, JSON_UNESCAPED_UNICODE));
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findNode($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['invest', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id) {
        $this->findNode($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionOpen($id) {
        /** @var User $me */
        $me = Yii::$app->user->identity;
        $node = new Node([
            'user' => Yii::$app->user->identity,
            'type_id' => $id
        ]);

        if ($node->user->account < $node->type->stake) {
            Yii::$app->session->setFlash('error', Yii::t('app', Invoice::$statuses['insufficient_funds']));
            return $this->redirect(['plan']);
        }

        $transaction = Yii::$app->db->beginTransaction();
        if (!$me->hasNodes()) {
            $referral = $me->referral;
            if ($referral) {
                if ($referral->hasNodes()) {
                    $referral->account += Type::get($id)->stake * 0.075;
                    $referral->update(false, ['account']);
                } else {
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The referral did not receive a bonus'));
                }
            }
        }

        $node->user->account -= $node->type->stake;
        try {
            if ($node->user->update(true, ['account']) && $node->invest()) {
                do {
                    $i = Node::rise();
                }
                while($i > 0);
                $transaction->commit();
                Yii::$app->session->setFlash('success', Yii::t('app', 'The plan is open'));
            }
        }
        catch(Exception $ex) {
            $transaction->rollBack();
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }

        return $this->redirect(['invest', 'user' => Yii::$app->user->identity->name]);
    }

    public function actionNode($id) {

        return $this->render('node', [
            'model' => Node::findOne($id)
        ]);
    }

    /**
     * Finds the Type model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Type the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Type::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

views/user/_form.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\models\User;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

function submit($label) {
    echo '<div class="form-group">';
    echo Html::submitButton($label, ['class' => 'btn btn-success']);
    echo '</div>';
}

$form = ActiveForm::begin();

if ($model->ref_name && $model->isNewRecord): ?>
    <div class="form-group">
        <?= Yii::t('app', 'Referral') . ': ' . $model->ref_name; ?>
    </div>
<?php endif;
if ($model->isNewRecord) {
    echo $form->field($model, 'name');
}
echo $form->field($model, 'email');
if ('signup' == $model->scenario) {
    echo $form->field($model, 'password')->passwordInput();
}
echo $form->field($model, 'skype');
if (!$model->isNewRecord) {
    echo $form->field($model, 'duration');
}
if ($model->isNewRecord || Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'perfect');
}
else {
    $a = Html::a('обратитесь к адмнинистратору', ['feedback/create', 'template' => 'wallet']);
    echo "<div class='form-group'>Для изменения кошелька $a</div>";
}
if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'account');
    echo $form->field($model, 'status')->dropDownList(User::statuses());
}

if (Yii::$app->user->isGuest) {
    submit(Yii::t('app', 'Signup'));
}
else {
    if ($model->isNewRecord) {
        submit(Yii::t('app', 'Create'));
    }
    else {
        submit(Yii::t('app', 'Update'));
    }
}

ActiveForm::end();

echo '</div>';

views/user/_search.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'hash') ?>

    <?= $form->field($model, 'auth') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/account.php
<?php
/**
 * @link http://zenothing.com/
 */
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="account">
    <h1><?= Yii::t('app', 'Accounts') ?></h1>
    <?php $form = ActiveForm::begin(); ?>
    <table class="table">
        <?php
        foreach($model as $key => $value) {
            echo Html::tag('tr',
                Html::tag('td', Yii::t('app', $key)) .
                Html::tag('td', $value, ['data-name' => $key])
            );
        }
        ?>
    </table>
    <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary']); ?>
    <?= Html::a('Двигать матрицу', ['/matrix/rise'], ['class' => 'btn btn-primary']) ?>
    <?php ActiveForm::end(); ?>
</div>

views/user/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::$app->user->isGuest ? Yii::t('app', 'Signup') : Yii::t('app', 'Create User');
?>
<div class="user-create">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\models\User;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', Yii::$app->user->identity->isManager() ? 'Users' : 'Sponsors');

$columns = [
    [
        'attribute' => 'name',
        'format' => 'html',
        'value' => function(User $model) {
            return Html::a($model->name, ['view', 'name' => $model->name]);
        }
    ],
    'email:email',
    'account',
    [
        'attribute' => 'perfect',
        'label' => Yii::t('app', 'Wallet')
    ],
    'skype',
    [
        'attribute' => 'ref_name',
        'format' => 'html',
        'value' => function(User $model) {
            return $model->ref_name ? Html::a($model->ref_name, ['view', 'name' => $model->ref_name]) : null;
        }
    ]
];

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    $columns[] = [
        'format' => 'html',
        'contentOptions' => ['class' => 'action'],
        'value' => function(User $model) {
            return Html::a('', ['update', 'name' => $model->name], ['class' => 'glyphicon glyphicon-pencil']);
        }
    ];
}
?>
<div class="user-index">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columns,
    ]); ?>

</div>

views/user/journal.php
<?php
/**
 * @link http://zenothing.com/
*/

/**
 * @var app\models\Record $record
 */

use app\models\User;

$info = $record->info;
if (!$info) {
    echo '';
}
elseif (isset($info['status'])) {
    echo Yii::t('app', 'Status') . ': ' . User::statuses()[$info['status']];
}
elseif (isset($info['account'])) {
    echo Yii::t('app', 'Account') . ': ' . $info['account'];
}
else {
    $key = key($info);
    echo "$key: " . $info[$key];
}

views/user/login.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Login */
/* @var $form ActiveForm */

$this->title = Yii::t('app', 'Login');
?>
<div class="user-login">
    <h1 class="bagatelle"><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'remember')->checkbox() ?>

    <div class="form-group">
        <?= Yii::t('app', 'You can recover <a href="{url}">your password</a>', [
            'url' => Url::to(['request']),
        ]); ?>
    </div>
    <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn btn-primary']) ?>
    <?php ActiveForm::end(); ?>
</div><!-- user-login -->

views/user/password.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$reset = !$model || 'reset' == $model->scenario;
$this->title = Yii::t('app', $reset ? 'Reset Password' : 'Set Password');
if (!$reset) {
    if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
        $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    }
    $this->params['breadcrumbs'][] = ['label' => $model->user_name, 'url' => ['view', 'name' => $model->user_name]];
    $this->params['breadcrumbs'][] = Yii::t('app', 'Password');
}

if ($message):
    echo "<div class=\"alert alert-danger\">$message</div>";
else:
    ?>
    <div class="user-password">
        <h1><?= $this->title ?></h1>
        <?php $form = ActiveForm::begin(); ?>

        <?php if (!$reset) {
            echo $form->field($model, 'password')->passwordInput();
        }
        elseif (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
            echo Html::hiddenInput('name', $model->user_name);
        }
        ?>
        <?= $form->field($model, 'new_password')->passwordInput() ?>
        <?= $form->field($model, 'repeat_password')->passwordInput() ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
<?php
endif;

views/user/request.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Request for password recovery');
$this->registerMetaTag([
    'name' => 'robots',
    'content' => 'noindex'
]);
?>
<div class="user-password">
    <h1><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoiceAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Update User') . ': ' . $model->name;
if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
}
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'name' => $model->name]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>