controllers/HomeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;


use app\models\Article;
use app\models\Record;
use app\models\search\Invoice;
use app\models\User;
use app\models\UserData;
use app\SQL;
use Yii;
use yii\web\Controller;
use yii\web\Cookie;
use yii\web\ForbiddenHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class HomeController extends Controller {
    public function actionIndex() {
        return $this->render('index', [
            'statistics' => $this->renderPartial('statistics', ['statistics' => static::statistics()]),
        ]);
    }

    public function actionLanguage($code = 'en') {
        $cookies = Yii::$app->response->cookies;
        if ('en' == $code) {
            $cookies->add(new Cookie([
                'name' => 'lang',
                'value' => 'en',
                'expire' => time() + 3600 * 24 * 30
            ]));
        }
        else {
            $cookies->remove('lang');
        }
        return $this->goBack();
    }

    public function actionPage($name) {
        $article = Article::fromFile($name);
        if (false !== $article->content) {
            return $this->render('page', [
                'model' => $article
            ]);
        }
        else {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Page not found.'));
            return $this->render('index');
        }
    }

    public function actionUpdate($name) {
        $article = new Article();
        if ($article->load(Yii::$app->request->post()) && $article->validate() && $article->saveFile()) {
            $this->redirect(['page', 'name' => $article->name]);
        }
        else {
            $article->name = $name;
            $article->loadFile();
        }

        if (false !== $article->content) {
            return $this->render('update', [
                'model' => $article
            ]);
        } else {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Page not found.'));
            return $this->render('index');
        }
    }

    public function actionBanner() {
        return $this->render('banner');
    }

    public function actionError() {
        $exception = Yii::$app->getErrorHandler()->exception;
        $message = $exception->getMessage();
        if ($exception instanceof ForbiddenHttpException) {
            $message = $message ? Yii::t('app', $message) : Yii::t('app', 'Forbidden');
        }
        if ($message) {
            Yii::$app->session->setFlash('error', $message);
        }
        return $this->render('error', [
            'exception' => $exception
        ]);
    }

    public static function statistics() {
        $started = strtotime(Record::find()->min('time'));
        $invested = SQL::query('SELECT count(*) FROM
            (SELECT id, (case when (reinvest_from is null) then 0 else 1 end) as reinvest
            FROM ((SELECT node_id as id, reinvest_from FROM archive)
            UNION (SELECT id, reinvest_from FROM node)) a GROUP BY id, reinvest_from)
            g GROUP BY reinvest ORDER BY reinvest');
        $invested = $invested->queryColumn();
        if (count($invested) < 2) {
            $invested = [0, 0];
        }
        return [
            'Started' => date('d-m-Y', $started),
            'Running days' => floor((time() - $started)/(3600 * 24)),
            'Users' => User::find()->count(),
            'Total deposited' => Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount > 0')->sum('amount'),
            'Total withdraw' => - Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount < 0')->sum('amount'),
            'Number of investments' => $invested[0],
            'Number of reinvestments' => $invested[1]
        ];
    }
}

controllers/UserController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\Account;
use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\Login;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\SQL;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\base\InvalidParamException;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class UserController extends Controller
{
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::className(),
                'plain' => ['view', 'update', 'index'],
                'manager' => ['complete', 'account'],
                'admin' => ['delete']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($name = null) {
        /* @var User $me */
        $me = Yii::$app->user->identity;
        $model = $name ? $this->findModel($name) : $me;
        if (!$name || $me->isManager() || $model->ref_name == $name || User::find()->where([
                'ref_name' => $me->name, 'name' => $name])->count() > 0) {
            return $this->render('view', [
                'model' => $model,
            ]);
        }
        throw new ForbiddenHttpException();
    }

    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->name != Yii::$app->user->identity->name && !Yii::$app->user->identity->isAdmin()) {
            throw new ForbiddenHttpException('Forbidden');
        }

        if ($model->load(Yii::$app->request->post())) {
            if (!Yii::$app->user->identity->isAdmin()) {
                if ($model->isAttributeChanged('email', false)) {
                    $model->generateCode();
                    $url = Url::to(['email', 'code' => $model->code], true);
                    $model->sendEmail('html', [
                        'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Email confirmation'),
                        'content' => Yii::t('app', 'To confirm your email click on the <a href="{url}">link</a>', [
                            'url' => $url,
                        ])
                    ]);
                    $model->setBundle(['email' => $model->email]);
                    $model->email = $model->getOldAttribute('email');
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The new email address will be changed after you confirm it'));
                }
                if ($model->isAttributeChanged('perfect', false)) {
                    $model->perfect = $model->getOldAttribute('perfect');
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Wallet can change admin only'));
                }
            }

            if ($model->save()) {
                return $this->redirect(['view', 'name' => $model->name]);
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSignup($referral = null) {
        $model = new User([
            'scenario' => 'signup',
            'ref_name' => $referral
        ]);
        if (preg_match('|U\w{7}|', $model->name)) {
            $model->addError('name', Yii::t('app', Yii::t('app', 'Username cannot be in the format of Perfect Money wallet')));
        }
        elseif ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->generateCode();
            $model->status = User::PLAIN;
            $model->setBundleFromAttributes(['hash'], true);
            $model->save(false);
            $url = Url::to(['email', 'code' => $model->code], true);
            if ($model->sendEmail('html', [
                'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Signup'),
                'content' => Yii::t('app', 'To confirm your registration click on the <a href="{url}">link</a>', [
                    'url' => $url,
                ])
            ])) {
                Yii::$app->session->setFlash('info', Yii::t('app', 'Check your email'));
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Email send error'));
            }
            return $this->redirect(['home/index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $model = new Login();

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                if (empty($user->hash)) {
                    Yii::$app->session->setFlash('error', Yii::t('app',
                        Yii::t('app', 'Your account is not activated. Check your email')));
                }
                else {
                    $can = $user->canLogin();
                    if ($can && $user->validatePassword($model->password)) {
                        if ($user->status > 0) {
                            if (empty($user->auth)) {
                                $user->generateAuthKey();
                                $user->save();
                            }
                            if (Yii::$app->user->login($user, $model->remember ? $user->duration * 60 : 0)) {
                                return $this->redirect(['view']);
                            }
                            else {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
                            }
                        } else {
                            Yii::$app->session->setFlash('error', Yii::t('app', Yii::t('app', 'Your account is blocked')));
                        }
                    } else {
                        Journal::write('user', 'login_fail', $user->id);
                        if ($can) {
                            Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                        } else {
                            $record = Record::find()->where([
                                'object_id' => $user->id,
                                'event' => 'login_fail'
                            ])->orderBy(['time' => SORT_DESC])->one();
                            Yii::$app->session->setFlash('error',
                                Yii::t('app', 'You have exceeded the maximum number of login attempts, you will be able to enter after {time}', [
                                    'time' => $record->time
                                ]));
                        }
                    }
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->redirect(['home/index']);
    }

    public function actionEmail($code) {
        /** @var User $user */
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
            $user = User::findOne(['name' => $code]);
        }
        else {
            $user = preg_match('|^[\w\-_]{64}$|', $code) ? User::findOne(['code' => $code]) : null;
        }
        if ($user) {
            $bundle = $user->getBundle();
            $message = empty($user->hash) ? 'Congratulations. You have successfully activated!' : 'Your email changed!';
            foreach($bundle as $name => $value) {
                $user->$name = $value;
            }
            $user->code = null;
            $user->setBundle(null);
            if ($user->save()) {
                Yii::$app->session->addFlash('success', Yii::t('app', $message));
                Yii::$app->user->login($user);
                return $this->redirect(['user/view']);
            }
            else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
            }
        }
        else {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Invalid code'));
        }
        return $this->redirect(['home/index']);
    }

    public function actionPassword($code = null, $name = null) {
        /** @var User $user */
        $message = null;
        $model = null;
        if (isset($_POST['name'])) {
            $name = $_POST['name'];
        }
        if ($name) {
            if (Yii::$app->user->identity->isAdmin() || $name == Yii::$app->user->identity->name) {
                $user = User::findOne(['name' => $name]);
            }
            else {

views/home/banner.php
<?php
use yii\helpers\Html;
$sizes = [
    125 => 125,
    468 => 60,
    728 => 90
];
function banner($size) {
    $origin = 'http://' . $_SERVER['HTTP_HOST'];
    $url = $origin . "/img/$size.gif";
    return Html::a(Html::img($url, [
            'alt' => Yii::$app->name
        ]) .
        Html::script('', ['data-src' => 'http://zenothing.com/statistics.js']),
        $origin, ['target' => '_blank']);
}
?>
<div class="banners">
    <h1><?= Yii::t('app', 'Advertisement') ?></h1>
    <?php foreach([125, 468, 728] as $size): ?>
        <div id="<?= $size ?>">
            <h2><?= $size . 'x' . $sizes[$size] ?></h2>
            <?= banner($size) ?>
            <div class="form-group">
                <label for="<?= 'control' . $size ?>"><?= Yii::t('app', 'Code') ?>:</label>
                    <textarea id="<?= 'control' . $size ?>" class="form-control" rows="3"
                              style="font-family: courier"><?= htmlspecialchars(str_replace('data-src', 'src', banner($size))) ?></textarea>
            </div>
        </div>
    <?php endforeach; ?>
</div>

views/home/error.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;

/* @var $exception \app\JournalException */

$this->title = $exception->event;
$this->registerMetaTag([
    'name' => 'robots',
    'content' => 'noindex'
]);
?>
<div class="site-error">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

views/home/index.php
<?php
/**
 * @link http://zenothing.com/
 */
use app\God;
use app\widgets\Ext;
use yii\helpers\Html;

/**
 * @var string $statistics
 */

$this->title = Yii::$app->name;
$this->registerMetaTag([
    'name' => 'description',
    'content' => God::text('welcome')
]);

?>
<div class="home-index">
    <?= Ext::stamp() ?>

    <div class="top">
        <div>
            <span>У</span>НИКАЛЬНЫЙ,
            <span>Л</span>ЕГКИЙ И
            <span>И</span>ННОВАЦИОННЫЙ МАРКЕТИНГ
        </div>
        <div>
            Попробуй работать в команде
            и ты обречен на успех!
        </div>
        <?= God::block('front') ?>
    </div>
    <div>
        <div class="interesting">
            <div>Мы заинтересованы в успехе каждого!!!</div>
            <div>
                <?= Html::a(Yii::t('app', 'Read more'), ['matrix/plan']) ?>
            </div>
            <div></div>
        </div>
        <div class="row">
            <div class="block">
                <div class="welcome">
                    <img src="/img/success-plant.jpg">
                    <div>
                        <h2>Добро пожаловать в команду!</h2>
                        <?= God::block('welcome') ?>
                    </div>
                </div>
                <?= God::block('description') ?>
                <div class="video">
                    <iframe
                        width="527"
                        height="324"
                        src="//www.youtube.com/embed/o4YH8TlJg7k"
                        frameborder="0"
                        allowfullscreen=""></iframe>
                </div>
                <?= God::block('start') ?>
                <div>
                    <?= Html::a(Yii::t('app', 'Join our team'), ['user/signup'], ['class' => 'button']) ?>
                </div>
            </div>
            <dl>
                <dt>Платежные системы</dt>
                <dd>
                    <img src="/img/perfectmoney.png" />
                </dd>
                <dt>Посещения</dt>
                <dd><?= $statistics ?></dd>
            </dl>
        </div>
    </div>
</div>

views/home/page.php
<?php
/**
 * @link http://zenothing.com/
*/
use yii\bootstrap\Html;

$title = $model->getTitle();
if ($title) {
    $this->title = $title;
}
?>
<div class="page">
    <?php
    if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
        echo Html::a(Yii::t('app', 'Update'), ['update', 'name' => $model->name], ['class' => 'btn btn-primary']);
    }
    ?>

    <article><?= $model->content ?></article>
</div>

views/home/statistics.php
<?php
/**
 * @link http://zenothing.com/
*/
use yii\helpers\Html;
?>
<div class="statistics">
<?php
foreach($statistics as $name => $value) {
    echo Html::tag('div', Html::tag('span', Yii::t('app', $name) . ':') . Html::tag('span', $value));
}
?>
</div>

views/home/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use dosamigos\ckeditor\CKEditor;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= Html::activeHiddenInput($model, 'name') ?>
    <?= $form->field($model, 'content')->widget(CKEditor::className(), [
        'preset' => 'full'
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Update'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>